### ISSUE TITLE
.NET 6 support

### ISSUE THREAD

**Issue by SeanFeldman** [thinktecture/Thinktecture.Blazor#21]
The released version only supports .NET 7. Full disclaimer, I haven't looked at all the packages as I was after `Thinktecture.Blazor.PwaUpdate` only, and I'm not sure if anything would prevent multi-targetting to add support for .NET 6 as well. Would you be open to targeting .NET 6? Thank you.

**Comment by patrickjahr** [comment]
Yes, of course, I can do that. Give me two days that should be the new version released :-)
